#ifndef CTFP_MATH_H
#define CTFP_MATH_H

double ctfp_acos(double x);
float ctfp_acosf(float x);
double ctfp_acosh(double x);
float ctfp_acoshf(float x);
long double ctfp_acoshl(long double x);
long double ctfp_acoshl(long double x);
long double ctfp_acoshl(long double x);
long double ctfp_acosl(long double x);
long double ctfp_acosl(long double x);
double ctfp_asin(double x);
float ctfp_asinf(float x);
double ctfp_asinh(double x);
float ctfp_asinhf(float x);
long double ctfp_asinhl(long double x);
long double ctfp_asinhl(long double x);
long double ctfp_asinhl(long double x);
long double ctfp_asinl(long double x);
long double ctfp_asinl(long double x);
double ctfp_atan2(double y, double x);
float ctfp_atan2f(float y, float x);
long double ctfp_atan2l(long double y, long double x);
long double ctfp_atan2l(long double y, long double x);
double ctfp_atan(double x);
float ctfp_atanf(float x);
double ctfp_atanh(double x);
float ctfp_atanhf(float x);
long double ctfp_atanhl(long double x);
long double ctfp_atanhl(long double x);
long double ctfp_atanl(long double x);
long double ctfp_atanl(long double x);
double ctfp_cbrt(double x);
float ctfp_cbrtf(float x);
long double ctfp_cbrtl(long double x);
long double ctfp_cbrtl(long double x);
double ctfp_ceil(double x);
float ctfp_ceilf(float x);
long double ctfp_ceill(long double x);
long double ctfp_ceill(long double x);
double ctfp_copysign(double x, double y);
float ctfp_copysignf(float x, float y);
long double ctfp_copysignl(long double x, long double y);
long double ctfp_copysignl(long double x, long double y);
double ctfp___cos(double x, double y);
double ctfp_cos(double x);
float ctfp___cosdf(double x);
float ctfp_cosf(float x);
double ctfp_cosh(double x);
float ctfp_coshf(float x);
long double ctfp_coshl(long double x);
long double ctfp_coshl(long double x);
long double ctfp_coshl(long double x);
long double ctfp___cosl(long double x, long double y);
long double ctfp_cosl(long double x);
double ctfp_erf(double x);
float ctfp_erff(float x);
long double ctfp_erfl(long double x);
long double ctfp_erfl(long double x);
long double ctfp_erfl(long double x);
double ctfp_exp10(double x);
float ctfp_exp10f(float x);
long double ctfp_exp10l(long double x);
long double ctfp_exp10l(long double x);
double ctfp_exp2(double x);
float ctfp_exp2f(float x);
long double ctfp_exp2l(long double x);
long double ctfp_exp2l(long double x);
double ctfp_exp(double x);
float ctfp_expf(float x);
long double ctfp_expl(long double x);
long double ctfp_expl(long double x);
long double ctfp_expl(long double x);
double ctfp_expm1(double x);
float ctfp_expm1f(float x);
long double ctfp_expm1l(long double x);
long double ctfp_expm1l(long double x);
long double ctfp_expm1l(long double x);
double ctfp___expo2(double x);
float ctfp___expo2f(float x);
double ctfp_fabs(double x);
float ctfp_fabsf(float x);
long double ctfp_fabsl(long double x);
long double ctfp_fabsl(long double x);
double ctfp_fdim(double x, double y);
float ctfp_fdimf(float x, float y);
long double ctfp_fdiml(long double x, long double y);
long double ctfp_fdiml(long double x, long double y);
int ctfp_finite(double x);
int ctfp_finitef(float x);
double ctfp_floor(double x);
float ctfp_floorf(float x);
long double ctfp_floorl(long double x);
long double ctfp_floorl(long double x);
double ctfp_fma(double x, double y, double z);
double ctfp_fma(double x, double y, double z);
float ctfp_fmaf(float x, float y, float z);
long double ctfp_fmal(long double x, long double y, long double z);
long double ctfp_fmal(long double x, long double y, long double z);
double ctfp_fmax(double x, double y);
float ctfp_fmaxf(float x, float y);
long double ctfp_fmaxl(long double x, long double y);
long double ctfp_fmaxl(long double x, long double y);
double ctfp_fmin(double x, double y);
float ctfp_fminf(float x, float y);
long double ctfp_fminl(long double x, long double y);
long double ctfp_fminl(long double x, long double y);
double ctfp_fmod(double x, double y);
float ctfp_fmodf(float x, float y);
long double ctfp_fmodl(long double x, long double y);
long double ctfp_fmodl(long double x, long double y);
int ctfp___fpclassify(double x);
int ctfp___fpclassifyf(float x);
int ctfp___fpclassifyl(long double x);
int ctfp___fpclassifyl(long double x);
int ctfp___fpclassifyl(long double x);
double ctfp_frexp(double x, int *e);
float ctfp_frexpf(float x, int *e);
long double ctfp_frexpl(long double x, int *e);
long double ctfp_frexpl(long double x, int *e);
double ctfp_hypot(double x, double y);
float ctfp_hypotf(float x, float y);
long double ctfp_hypotl(long double x, long double y);
long double ctfp_hypotl(long double x, long double y);
int ctfp_ilogb(double x);
int ctfp_ilogbf(float x);
int ctfp_ilogbl(long double x);
int ctfp_ilogbl(long double x);
int ctfp_ilogbl(long double x);
double ctfp_j0(double x);
float ctfp_j0f(float x);
double ctfp_j1(double x);
float ctfp_j1f(float x);
double ctfp_jn(int n, double x);
float ctfp_jnf(int n, float x);
double ctfp_ldexp(double x, int n);
float ctfp_ldexpf(float x, int n);
long double ctfp_ldexpl(long double x, int n);
double ctfp_lgamma(double x);
float ctfp_lgammaf(float x);
long double ctfp_lgammal(long double x);
long long ctfp_llrint(double x);
long long ctfp_llrintf(float x);
long long ctfp_llrintl(long double x);
long long ctfp_llrintl(long double x);
long long ctfp_llrintl(long double x);
long long ctfp_llround(double x);
long long ctfp_llroundf(float x);
long long ctfp_llroundl(long double x);
double ctfp_log10(double x);
float ctfp_log10f(float x);
long double ctfp_log10l(long double x);
long double ctfp_log10l(long double x);
long double ctfp_log10l(long double x);
double ctfp_log1p(double x);
float ctfp_log1pf(float x);
long double ctfp_log1pl(long double x);
long double ctfp_log1pl(long double xm1);
long double ctfp_log1pl(long double x);
double ctfp_log2(double x);
float ctfp_log2f(float x);
long double ctfp_log2l(long double x);
long double ctfp_log2l(long double x);
long double ctfp_log2l(long double x);
double ctfp_logb(double x);
float ctfp_logbf(float x);
long double ctfp_logbl(long double x);
long double ctfp_logbl(long double x);
double ctfp_log(double x);
float ctfp_logf(float x);
long double ctfp_logl(long double x);
long double ctfp_logl(long double x);
long double ctfp_logl(long double x);
long ctfp_lrint(double x);
long ctfp_lrint(double x);
long ctfp_lrintf(float x);
long ctfp_lrintl(long double x);
long ctfp_lrintl(long double x);
long ctfp_lrintl(long double x);
long ctfp_lround(double x);
long ctfp_lroundf(float x);
long ctfp_lroundl(long double x);
double ctfp_modf(double x, double *iptr);
float ctfp_modff(float x, float *iptr);
long double ctfp_modfl(long double x, long double *iptr);
long double ctfp_modfl(long double x, long double *iptr);
double ctfp_nan(const char *s);
float ctfp_nanf(const char *s);
long double ctfp_nanl(const char *s);
double ctfp_nearbyint(double x);
float ctfp_nearbyintf(float x);
long double ctfp_nearbyintl(long double x);
long double ctfp_nearbyintl(long double x);
double ctfp_nextafter(double x, double y);
float ctfp_nextafterf(float x, float y);
long double ctfp_nextafterl(long double x, long double y);
long double ctfp_nextafterl(long double x, long double y);
long double ctfp_nextafterl(long double x, long double y);
double ctfp_nexttoward(double x, long double y);
double ctfp_nexttoward(double x, long double y);
float ctfp_nexttowardf(float x, long double y);
long double ctfp_nexttowardl(long double x, long double y);
long double ctfp___polevll(long double x, const long double *P, int n);
double ctfp_pow(double x, double y);
float ctfp_powf(float x, float y);
long double ctfp_powl(long double x, long double y);
long double ctfp_powl(long double x, long double y);
long double ctfp_powl(long double x, long double y);
double ctfp_remainder(double x, double y);
float ctfp_remainderf(float x, float y);
long double ctfp_remainderl(long double x, long double y);
long double ctfp_remainderl(long double x, long double y);
int ctfp___rem_pio2(double x, double *y);
int ctfp___rem_pio2f(float x, double *y);
int ctfp___rem_pio2_large(double *x, double *y, int e0, int nx, int prec);
int ctfp___rem_pio2l(long double x, long double *y);
double ctfp_remquo(double x, double y, int *quo);
float ctfp_remquof(float x, float y, int *quo);
long double ctfp_remquol(long double x, long double y, int *quo);
long double ctfp_remquol(long double x, long double y, int *quo);
double ctfp_rint(double x);
float ctfp_rintf(float x);
long double ctfp_rintl(long double x);
long double ctfp_rintl(long double x);
double ctfp_round(double x);
float ctfp_roundf(float x);
long double ctfp_roundl(long double x);
long double ctfp_roundl(long double x);
double ctfp_scalb(double x, double fn);
float ctfp_scalbf(float x, float fn);
double ctfp_scalbln(double x, long n);
float ctfp_scalblnf(float x, long n);
long double ctfp_scalblnl(long double x, long n);
long double ctfp_scalblnl(long double x, long n);
double ctfp_scalbn(double x, int n);
float ctfp_scalbnf(float x, int n);
long double ctfp_scalbnl(long double x, int n);
long double ctfp_scalbnl(long double x, int n);
int ctfp___signbit(double x);
int ctfp___signbitf(float x);
int ctfp___signbitl(long double x);
int ctfp___signbitl(long double x);
double ctfp_significand(double x);
float ctfp_significandf(float x);
double ctfp___sin(double x, double y, int iy);
double ctfp_sin(double x);
void ctfp_sincos(double x, double *ctfp_sin, double *ctfp_cos);
void ctfp_sincosf(float x, float *ctfp_sin, float *ctfp_cos);
void ctfp_sincosl(long double x, long double *ctfp_sin, long double *ctfp_cos);
void ctfp_sincosl(long double x, long double *ctfp_sin, long double *ctfp_cos);
float ctfp___sindf(double x);
float ctfp_sinf(float x);
double ctfp_sinh(double x);
float ctfp_sinhf(float x);
long double ctfp_sinhl(long double x);
long double ctfp_sinhl(long double x);
long double ctfp_sinhl(long double x);
long double ctfp___sinl(long double x, long double y, int iy);
long double ctfp_sinl(long double x);
long double ctfp_sinl(long double x);
double ctfp___tan(double x, double y, int odd);
double ctfp_tan(double x);
float ctfp___tandf(double x, int odd);
float ctfp_tanf(float x);
double ctfp_tanh(double x);
float ctfp_tanhf(float x);
long double ctfp_tanhl(long double x);
long double ctfp_tanhl(long double x);
long double ctfp_tanhl(long double x);
long double ctfp___tanl(long double x, long double y, int odd);
long double ctfp_tanl(long double x);
long double ctfp_tanl(long double x);
double ctfp_tgamma(double x);
float ctfp_tgammaf(float x);
long double ctfp_tgammal(long double x);
long double ctfp_tgammal(long double x);
long double ctfp_tgammal(long double x);
double ctfp_trunc(double x);
float ctfp_truncf(float x);
long double ctfp_truncl(long double x);
long double ctfp_truncl(long double x);

#endif
